#ifndef SIMULATOR_H
#define SIMULATOR_H

#define MAXIMUM_SIMULATION_TIME 100000
#define MAXIMUM_PERIOD_TASKS 13
#define MAXIMUM_APERIOD_TASKS 13
#define MAXIMUM_COMPUTING_PERIOD 100000
#define MAXIMUM_EXECUTING_PERIOD 100000
#define MAXIMUM_DEADLINE_PERIOD 100000
#define MAXIMUM_ARRIVAL_PERIOD 100000

typedef struct Simulator{
	int executingPeriod;
} Simulator;

#endif // SIMULATOR_H
